twig_component:
#  anonymous_template_directory: 'themes/%env(APP_THEME)%/components'
  anonymous_template_directory: 'components/'
  defaults:
    # Namespace & directory for components
#    '%kernel.project_dir%/templates/themes/%env(APP_THEME)%/components': 'components/'
    App\Components\: 'components/'